# Generated by Django 5.0.6 on 2024-05-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_complaint_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='price',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
